apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-docker-repo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-docker-repo
    app.kubernetes.io/part-of: sample-docker-repo
  name: sample-docker-repo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: sample-docker-repo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sample-docker-repo
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/susdas-tenant/sample-docker-repo/sample-docker-repo@sha256:3457292b3c13be82bc2c0596ad7b64c0e283e910415be626238ac954d1da7fe8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
